import { AnimatePresence, motion } from 'motion/react'
import { Award, Binoculars, CheckCircle2, Earth, Fish, MapPinned, Scale, Trash2 } from 'lucide-react'
import { useState } from 'react'
import ExhibitHeader from '../components/ExhibitHeader.jsx'
import { ETHICS_SECTIONS, JURISDICTIONS, LAW_HISTORY } from '../data/ethics.js'

const SECTION_ICONS = { 'locate-rule': MapPinned, 'decide-catch': Scale, 'care-for-fish': Fish, 'tackle-afterlife': Trash2, 'watch-water': Binoculars }

export default function EthicsHall({ hall }) {
  const [jurisdiction, setJurisdiction] = useState(0)
  const [signedName, setSignedName] = useState('')
  const [signed, setSigned] = useState(false)
  const activePlace = JURISDICTIONS[jurisdiction]
  const submit = (event) => { event.preventDefault(); if (signedName.trim()) setSigned(true) }
  return <main className="min-h-screen bg-[#eef2ee] text-zinc-800 px-4 md:px-8 py-14 md:py-20 relative overflow-hidden font-sans"><div className="absolute top-[30%] -left-48 w-[38rem] h-[38rem] rounded-full bg-emerald-100/40 blur-[150px] pointer-events-none" /><div className="max-w-7xl mx-auto relative z-10 space-y-16"><ExhibitHeader eyebrow="HALL 07 / 第七展厅" title={hall.title} summary="钓获不是故事的终点。法律决定最低边界，鱼体处置与水域变化则追问人在合法之外还应怎样行动。" />
    <section className="grid lg:grid-cols-[280px_1fr] gap-8"><div className="lg:sticky lg:top-24 self-start"><span className="text-[10px] font-mono text-zinc-500">RULES THROUGH TIME</span><h2 className="text-3xl font-bold text-zinc-900 mt-2">规则为何出现</h2><p className="text-sm leading-7 text-zinc-600 mt-4">不同时代的规则保护过资源、税赋、权力、祭祀空间和公共安全，它们并不共享同一种理由。</p></div><div className="relative pl-7 border-l border-zinc-300 space-y-8">{LAW_HISTORY.map((item, index) => <motion.article initial={{ opacity: 0, x: 18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} key={item.period} className="relative pb-8 border-b border-zinc-200"><span className="absolute -left-[34px] top-1 w-3.5 h-3.5 rounded-full bg-white border border-zinc-400" /><span className="text-[10px] font-mono text-zinc-500">{String(index + 1).padStart(2, '0')} / {item.period}</span><h3 className="text-lg font-bold text-zinc-900 mt-2">{item.title}</h3><p className="text-sm leading-7 text-zinc-600 mt-3">{item.text}</p></motion.article>)}</div></section>
    <section className="p-5 md:p-8 rounded-2xl border border-zinc-200 bg-white/70 space-y-7"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><span className="text-[10px] font-mono text-zinc-500 flex items-center gap-2"><Earth size={14} />MANAGEMENT MODELS</span><h2 className="text-2xl font-bold text-zinc-900 mt-2">五个国家和地区的规则查找路径</h2></div><span className="text-xs text-zinc-500">规则随地点、日期、物种和水域变化</span></div><nav className="flex gap-2 overflow-x-auto" aria-label="国家和地区">{JURISDICTIONS.map((item, index) => <button type="button" onClick={() => setJurisdiction(index)} className={`flex-none px-4 py-2.5 rounded-full border text-xs ${jurisdiction === index ? 'bg-zinc-900 border-zinc-900 text-white' : 'bg-white border-zinc-200 text-zinc-600'}`} key={item.place}>{item.place}</button>)}</nav><AnimatePresence mode="wait"><motion.div key={activePlace.place} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="grid md:grid-cols-[220px_1fr] gap-6 pt-4 border-t border-zinc-200"><div><span className="text-[9px] font-mono text-zinc-400">MANAGER / 管理主体</span><p className="text-sm font-semibold text-zinc-900 mt-2 leading-6">{activePlace.manager}</p></div><ol className="grid sm:grid-cols-2 gap-3">{activePlace.questions.map((question, index) => <li className="p-4 rounded-xl bg-zinc-50 border border-zinc-100 text-xs leading-6 flex gap-3" key={question}><span className="text-[9px] font-mono text-zinc-400">0{index + 1}</span>{question}</li>)}</ol></motion.div></AnimatePresence></section>
    <section><div className="max-w-2xl mb-7"><span className="text-[10px] font-mono text-zinc-500">FROM CAST TO DEPARTURE</span><h2 className="text-3xl font-bold text-zinc-900 mt-2">法律边界之后，还有五个判断</h2></div><div className="grid md:grid-cols-5 gap-px bg-zinc-300 border border-zinc-300">{ETHICS_SECTIONS.map((section, index) => { const Icon = SECTION_ICONS[section.id]; return <motion.article whileHover={{ y: -5 }} key={section.id} className="bg-[#f8faf8] p-5 md:min-h-[330px] flex flex-col justify-between"><div className="flex items-center justify-between"><span className="text-[9px] font-mono text-zinc-400">0{index + 1}</span><Icon size={18} className="text-zinc-500" /></div><div><h3 className="text-base font-bold text-zinc-900">{section.title}</h3><strong className="block text-xs leading-6 text-zinc-700 mt-3">{section.question}</strong><p className="text-xs leading-6 text-zinc-500 mt-3">{section.text}</p></div></motion.article> })}</div></section>
    <section className="relative overflow-hidden rounded-2xl border border-zinc-200 bg-white/75 p-6 md:p-10 grid md:grid-cols-[1.2fr_0.8fr] gap-8 items-center"><div className="space-y-5"><span className="text-[10px] font-mono text-zinc-500 flex items-center gap-2"><Award size={14} />WATERSIDE PLEDGE / 水边承诺</span><h2 className="text-2xl font-bold text-zinc-900">把水边恢复到来时的样子</h2><p className="text-sm leading-7 text-zinc-600">我会先确认规则，按要求处置鱼获；缩短鱼体离水时间；带走断线、鱼钩、包装和剩余饵料；发现异常水情时，记录并向当地管理部门反映。</p>{!signed ? <form onSubmit={submit} className="flex flex-col sm:flex-row gap-2 max-w-lg"><label className="sr-only" htmlFor="pledge-name">署名</label><input id="pledge-name" required maxLength={20} value={signedName} onChange={(event) => setSignedName(event.target.value)} placeholder="写下姓名或水边称呼" className="flex-1 h-11 px-4 rounded-xl border border-zinc-200 bg-white text-sm outline-none focus:border-zinc-500" /><button type="submit" className="h-11 px-5 rounded-xl bg-zinc-900 text-white text-xs">签署承诺</button></form> : <div className="flex items-center gap-2 text-sm font-semibold text-emerald-800"><CheckCircle2 size={17} />承诺已签署</div>}</div><div className="min-h-56 flex items-center justify-center"><AnimatePresence mode="wait">{signed ? <motion.div initial={{ scale: 1.8, rotate: -20, opacity: 0 }} animate={{ scale: 1, rotate: -7, opacity: 1 }} transition={{ type: 'spring', damping: 13 }} className="w-44 h-44 rounded-full border-4 border-red-700/70 text-red-800 flex flex-col items-center justify-center text-center p-5"><strong className="text-xl">水边守护</strong><span className="text-sm mt-2 max-w-[120px] break-words">{signedName}</span><small className="text-[8px] font-mono mt-3">SIGNED LOCALLY</small></motion.div> : <div className="w-44 h-44 rounded-full border border-dashed border-zinc-300 flex items-center justify-center text-[10px] font-mono text-zinc-400 text-center p-8">签署后生成本地数字印记<br />不会上传姓名</div>}</AnimatePresence></div></section>
  </div></main>
}
