import { motion } from 'motion/react'
import { ArrowUpRight } from 'lucide-react'
import { useMemo, useState } from 'react'

export default function AnglerIdentityStage({ groups, records, onOpen }) {
  const [groupId, setGroupId] = useState(groups[0].id)
  const group = groups.find((item) => item.id === groupId)
  const visible = useMemo(() => records.filter((record) => record.groupId === groupId || group.recordIds.includes(record.id)), [group.recordIds, groupId, records])
  const [recordId, setRecordId] = useState(null)
  const active = visible.find((item) => item.id === recordId) || visible[0]
  const chooseGroup = (id) => { setGroupId(id); setRecordId(null) }
  return <section className="space-y-7" aria-label="水边身份图谱"><nav className="flex gap-7 overflow-x-auto border-b border-stone-300" aria-label="水边身份分类">{groups.map((item) => <button type="button" className={`relative flex-none pb-3 text-xs ${groupId === item.id ? 'font-semibold text-zinc-900' : 'text-zinc-500'}`} onClick={() => chooseGroup(item.id)} key={item.id}>{item.label}{groupId === item.id ? <motion.span layoutId="identity-line" className="absolute inset-x-0 bottom-0 h-0.5 bg-zinc-900" /> : null}</button>)}</nav><div className="grid min-h-[540px] border-y border-stone-300 lg:grid-cols-[260px_220px_1fr]"><aside className="border-b border-stone-300 p-5 lg:border-b-0 lg:border-r md:p-7"><small className="font-mono text-[9px] text-zinc-400">IDENTITY GROUP / 身份类别</small><h2 className="mt-2 text-2xl font-semibold text-zinc-900">{group.label}</h2><p className="mt-4 text-sm leading-7 text-zinc-600">{group.description}</p></aside><nav className="max-h-[540px] overflow-y-auto border-b border-stone-300 lg:border-b-0 lg:border-r" aria-label={`${group.label}人物索引`}>{visible.length ? visible.map((record, index) => <button type="button" key={record.id} onClick={() => setRecordId(record.id)} className={`w-full border-b border-stone-200 p-4 text-left ${active?.id === record.id ? 'bg-white text-zinc-950' : 'bg-white/35 text-zinc-500 hover:bg-white/70'}`}><small className="block font-mono text-[8px] text-zinc-400">{String(index + 1).padStart(2, '0')}</small><span className="mt-1 block text-xs leading-5">{record.title}</span></button>) : <p className="p-5 text-xs leading-6 text-zinc-500">该类别的资料仍在整理，不设置虚拟人物。</p>}</nav>{active ? <motion.article key={active.id} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} className="flex min-w-0 flex-col justify-between bg-[#f8f6f2] p-6 md:p-9"><div>{active.image ? <img src={active.image} alt={active.title} className="mb-7 max-h-60 w-full object-contain object-left" /> : null}<small className="font-mono text-[9px] text-zinc-400">{active.kind}</small><h2 className="mt-2 text-3xl font-semibold text-zinc-900">{active.title}</h2><p className="mt-5 max-w-2xl text-sm leading-8 text-zinc-600">{active.text}</p></div><button type="button" onClick={() => onOpen(active)} aria-label={`查看${active.title}`} className="mt-8 inline-flex items-center gap-2 self-start border-b border-zinc-900 pb-1 text-xs text-zinc-900">查看完整人物记录 <ArrowUpRight size={13} aria-hidden="true" /></button></motion.article> : null}</div></section>
}
